SELECT
    coin_id,
    symbol,
    name,
    image_url,
    SAFE_CAST(current_price AS NUMERIC) AS current_price_usd,
    SAFE_CAST(market_cap AS NUMERIC) AS market_cap_usd,
    SAFE_CAST(market_cap_rank AS INT64) AS market_cap_rank,
    SAFE_CAST(fully_diluted_valuation AS NUMERIC) AS fully_diluted_valuation_usd,
    SAFE_CAST(total_volume AS NUMERIC) AS total_volume_24h_usd,
    SAFE_CAST(high_24h AS NUMERIC) AS high_24h_usd,
    SAFE_CAST(low_24h AS NUMERIC) AS low_24h_usd,
    SAFE_CAST(price_change_24h AS NUMERIC) AS price_change_24h_usd,
    SAFE_CAST(price_change_percentage_24h AS FLOAT64) AS price_change_percentage_24h,
    SAFE_CAST(price_change_percentage_1h_in_currency AS FLOAT64) AS price_change_percentage_1h,
    SAFE_CAST(price_change_percentage_7d_in_currency AS FLOAT64) AS price_change_percentage_7d,
    SAFE_CAST(circulating_supply AS NUMERIC) AS circulating_supply,
    SAFE_CAST(total_supply AS NUMERIC) AS total_supply,
    SAFE_CAST(max_supply AS NUMERIC) AS max_supply,
    SAFE_CAST(ath AS NUMERIC) AS ath_usd,
    SAFE_CAST(ath_change_percentage AS FLOAT64) AS ath_change_percentage,
    ath_date,
    SAFE_CAST(atl AS NUMERIC) AS atl_usd,
    SAFE_CAST(atl_change_percentage AS FLOAT64) AS atl_change_percentage,
    atl_date,
    SAFE_CAST(roi_percentage AS FLOAT64) AS roi_percentage,
    last_updated,
    extracted_at
FROM {{ source('staging', 'stg_raw_crypto_market_coins') }}