name: 'enterprise_data_platform'
version: '1.0.0'
config-version: 2

profile: 'enterprise_bigquery'

model-paths: ["models"]
macro-paths: ["macros"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  enterprise_data_platform:
    marts:
      +materialized: table